language: ruby

rvm:
  - 1.9.3
  - 2.0.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzmq-dev

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.net#miu-dev" 
    use_notice: true
    skip_join: true

